// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oazA1YFPiZCNccrS5tDgY4
// Component: nBTO5Pj6Yru
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useTheme } from "./PlasmicGlobalVariant__Theme"; // plasmic-import: x3o5Jg0GQTk/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as projectcss from "./plasmic_todo_mvc.module.css"; // plasmic-import: oazA1YFPiZCNccrS5tDgY4/projectcss
import * as sty from "./PlasmicTask.module.css"; // plasmic-import: nBTO5Pj6Yru/css

export const PlasmicTask__VariantProps = new Array("state");

export const PlasmicTask__ArgProps = new Array("children");

function PlasmicTask__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    theme: useTheme()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(projectcss.all, projectcss.root_reset, sty.root, {
        [sty.root__global_theme_dark]: hasVariant(
          globalVariants,
          "theme",
          "dark"
        ),

        [sty.root__state_checked]: hasVariant(variants, "state", "checked"),
        [sty.root__state_editing]: hasVariant(variants, "state", "editing"),
        [sty.root__state_editing_global_theme_dark]:
          hasVariant(variants, "state", "editing") &&
          hasVariant(globalVariants, "theme", "dark")
      })}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__ck1RM, {
          [sty.freeBox__state_editing__ck1RMb5Yl]: hasVariant(
            variants,
            "state",
            "editing"
          ),

          [sty.freeBox__state_editing_global_theme_dark__ck1RMb5YlBeqsa]:
            hasVariant(variants, "state", "editing") &&
            hasVariant(globalVariants, "theme", "dark")
        })}
      >
        {(hasVariant(variants, "state", "editing") ? false : true) ? (
          <div
            className={classNames(projectcss.all, sty.freeBox__aTtbo, {
              [sty.freeBox__state_checked__aTtbOsWmur]: hasVariant(
                variants,
                "state",
                "checked"
              ),

              [sty.freeBox__state_checked_global_theme_dark__aTtbOsWmurBeqsa]:
                hasVariant(variants, "state", "checked") &&
                hasVariant(globalVariants, "theme", "dark"),
              [sty.freeBox__state_editing__aTtbob5Yl]: hasVariant(
                variants,
                "state",
                "editing"
              )
            })}
          >
            {(hasVariant(variants, "state", "checked") ? true : false) ? (
              <p.PlasmicImg
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(sty.img, {
                  [sty.img__state_checked]: hasVariant(
                    variants,
                    "state",
                    "checked"
                  ),

                  [sty.img__state_checked_global_theme_dark]:
                    hasVariant(variants, "state", "checked") &&
                    hasVariant(globalVariants, "theme", "dark"),
                  [sty.img__state_editing]: hasVariant(
                    variants,
                    "state",
                    "editing"
                  )
                })}
                displayHeight={
                  hasVariant(variants, "state", "checked") ? "23px" : "16px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(variants, "state", "checked") ? "23px" : "16px"
                }
                src={
                  hasVariant(variants, "state", "checked")
                    ? "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxZW0iIGhlaWdodD0iMWVtIiB2aWV3Qm94PSIwIDAgNTEyIDUxMiIgc3Ryb2tlLXdpZHRoPSIwIiBmaWxsPSJjdXJyZW50Q29sb3IiIHN0cm9rZT0iY3VycmVudENvbG9yIiBzdHlsZT0iZmlsbDogcmdiKDQsIDE0MywgNjQpOyI+PHBhdGggZD0iTTE3My44OTggNDM5LjQwNGwtMTY2LjQtMTY2LjRjLTkuOTk3LTkuOTk3LTkuOTk3LTI2LjIwNiAwLTM2LjIwNGwzNi4yMDMtMzYuMjA0YzkuOTk3LTkuOTk4IDI2LjIwNy05Ljk5OCAzNi4yMDQgMEwxOTIgMzEyLjY5IDQzMi4wOTUgNzIuNTk2YzkuOTk3LTkuOTk3IDI2LjIwNy05Ljk5NyAzNi4yMDQgMGwzNi4yMDMgMzYuMjA0YzkuOTk3IDkuOTk3IDkuOTk3IDI2LjIwNiAwIDM2LjIwNGwtMjk0LjQgMjk0LjQwMWMtOS45OTggOS45OTctMjYuMjA3IDkuOTk3LTM2LjIwNC0uMDAxeiIvPjwvc3ZnPg=="
                    : "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxZW0iIGhlaWdodD0iMWVtIiB2aWV3Qm94PSIwIDAgNTEyIDUxMiIgc3Ryb2tlLXdpZHRoPSIwIiBmaWxsPSJjdXJyZW50Q29sb3IiIHN0cm9rZT0iY3VycmVudENvbG9yIj48cGF0aCBkPSJNMTczLjg5OCA0MzkuNDA0bC0xNjYuNC0xNjYuNGMtOS45OTctOS45OTctOS45OTctMjYuMjA2IDAtMzYuMjA0bDM2LjIwMy0zNi4yMDRjOS45OTctOS45OTggMjYuMjA3LTkuOTk4IDM2LjIwNCAwTDE5MiAzMTIuNjkgNDMyLjA5NSA3Mi41OTZjOS45OTctOS45OTcgMjYuMjA3LTkuOTk3IDM2LjIwNCAwbDM2LjIwMyAzNi4yMDRjOS45OTcgOS45OTcgOS45OTcgMjYuMjA2IDAgMzYuMjA0bC0yOTQuNCAyOTQuNDAxYy05Ljk5OCA5Ljk5Ny0yNi4yMDcgOS45OTctMzYuMjA0LS4wMDF6Ii8+PC9zdmc+"
                }
              />
            ) : null}
          </div>
        ) : null}
      </div>

      <div
        className={classNames(projectcss.all, sty.freeBox__tOgpk, {
          [sty.freeBox__global_theme_dark__tOgpkBeqsa]: hasVariant(
            globalVariants,
            "theme",
            "dark"
          ),

          [sty.freeBox__state_editing__tOgpkb5Yl]: hasVariant(
            variants,
            "state",
            "editing"
          ),

          [sty.freeBox__state_editing_global_theme_dark__tOgpkb5YlBeqsa]:
            hasVariant(variants, "state", "editing") &&
            hasVariant(globalVariants, "theme", "dark")
        })}
      >
        {(hasVariant(variants, "state", "editing") ? false : true) ? (
          <div
            className={classNames(projectcss.all, sty.freeBox__jHccM, {
              [sty.freeBox__state_checked__jHccMsWmur]: hasVariant(
                variants,
                "state",
                "checked"
              ),

              [sty.freeBox__state_editing__jHccMb5Yl]: hasVariant(
                variants,
                "state",
                "editing"
              )
            })}
          >
            {p.renderPlasmicSlot({
              defaultContents: "Some kind of text here",
              value: args.children,
              className: classNames(sty.slotTargetChildren, {
                [sty.slotTargetChildren__global_theme_dark]: hasVariant(
                  globalVariants,
                  "theme",
                  "dark"
                ),

                [sty.slotTargetChildren__state_checked]: hasVariant(
                  variants,
                  "state",
                  "checked"
                ),

                [sty.slotTargetChildren__state_checked_global_theme_dark]:
                  hasVariant(variants, "state", "checked") &&
                  hasVariant(globalVariants, "theme", "dark"),
                [sty.slotTargetChildren__state_editing]: hasVariant(
                  variants,
                  "state",
                  "editing"
                )
              })
            })}
          </div>
        ) : null}
        {(hasVariant(variants, "state", "editing") ? true : false) ? (
          <input
            data-plasmic-name={"textInput"}
            data-plasmic-override={overrides.textInput ?? overrides.textbox}
            className={classNames(projectcss.input, sty.textInput, {
              [sty.textInput__state_editing]: hasVariant(
                variants,
                "state",
                "editing"
              ),

              [sty.textInput__state_editing_global_theme_dark]:
                hasVariant(variants, "state", "editing") &&
                hasVariant(globalVariants, "theme", "dark")
            })}
            placeholder={"Some placeholder text"}
            type={"text"}
          />
        ) : null}
        {(hasVariant(variants, "state", "editing") ? false : true) ? (
          <div
            className={classNames(projectcss.all, sty.freeBox__xnn13, {
              [sty.freeBox__state_editing__xnn13B5Yl]: hasVariant(
                variants,
                "state",
                "editing"
              )
            })}
          >
            <button
              data-plasmic-name={"button"}
              data-plasmic-override={overrides.button}
              className={classNames(
                projectcss.button,
                projectcss.__wab_text,
                sty.button,
                {
                  [sty.button__state_editing]: hasVariant(
                    variants,
                    "state",
                    "editing"
                  )
                }
              )}
            >
              {"×"}
            </button>
          </div>
        ) : null}
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "img", "textInput", "textbox", "button"],
  img: ["img"],
  textInput: ["textInput", "textbox"],
  button: ["button"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTask__ArgProps,
      internalVariantPropNames: PlasmicTask__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicTask__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTask";
  } else {
    func.displayName = `PlasmicTask.${nodeName}`;
  }
  return func;
}

export const PlasmicTask = Object.assign(
  // Top-level PlasmicTask renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    textInput: makeNodeComponent("textInput"),
    button: makeNodeComponent("button"),
    // Metadata about props expected for PlasmicTask
    internalVariantProps: PlasmicTask__VariantProps,
    internalArgProps: PlasmicTask__ArgProps
  }
);

export default PlasmicTask;
/* prettier-ignore-end */
